inputs:
  location: "http://localhost:9000"
  key: "clowder_key"
  username: ""
  password: ""
  file_path: "full-path/allerton/pygeotemporal_parsers/"
  aggregate: "parse/allerton/aggregate"
  aggregate_header: "parse/allerton/aggrHeader"
  aggregate_file_type: ".csv"
  aggregate_path: "parse/allerton/aggregates/"
  dataset_upload_id: "DatasetID"
