inputs:
  location: "http://localhost:9000"
  key: "clowder_key"
  user: "clowder_username"
  password: "clowder_password"
  file_path: "full-path/pygeostreams_parsers/"
  timestamp: "TIMESTAMP"
  headers: 4
  verify: "flux"
  file_type: ".dat"
  new_files: "parse/flux_tower/flux_tower_new_files.csv"
  aggregate: "parse/flux_tower/flux_tower_aggregate"
  aggregate_file_type: ".csv"
  parse: "parse/flux_tower/flux_tower_parse.csv"
  downloads: "parse/flux_tower/flux_tower_files"
config:
  dataset_source_id: "DatasetID"
  dataset_upload_id: "DatasetID"
  sensor:
      geometry:
          type": Point
          coordinates: [-88.55511111, 40.15569444, 0]
      properties:
          region: "Illinois"
          type:
              id: "imlczo"
              title: "IMLCZO"
              location: "flux-tower"
              network: ""
          elevation:
              mean_sea_level: 0
              offset: 0
              offset_units: "meters"
          name: ""
          popupContent: ""
          huc: ""
parameters:
  u_star: "CSAT3 Sonic Anemometer"
  rslt_wnd_spd: "CSAT3 Sonic Anemometer"
  wnd_dir_compass: "CSAT3 Sonic Anemometer"
  Fc_li_wpl: "Li7500"
  LE_li_wpl: "Li7500"
  Hc_li: "Li7500"
  CO2_li_mean: "Li7500"
  H2O_li_mean: "Li7500"
  amb_press_li_mean: "Li7500"
  rho_a_li_mean: "Li7500"
  Precip_Tot: "TE525-L rain gauge"
  T_tmpr_rh_mean: "083E Temp and RH"
  e_tmpr_rh_mean: "083E Temp and RH"
  e_sat_tmpr_rh_mean: "083E Temp and RH"
  H2O_tmpr_rh_mean: "083E Temp and RH"
  RH_tmpr_rh_mean: "083E Temp and RH"
  CS655_Wcr_Avg: "CS655-L50 Reflectometer"
  CS655_Ec_Avg: "CS655-L50 Reflectometer"
  CS655_Tmpr_Avg: "CS655-L50 Reflectometer"
  NDVI_Avg: "SRS NDVI (a:fieldstop): Nr"
  PRI_Avg: "SRS PRI (a:fieldstop): Pr"
  D5TE_VWC_5cm_Avg: "5TE Soil Probe 5cm"
  D5TE_EC_5cm_Avg: "5TE Soil Probe 5cm"
  D5TE_T_5cm_Avg: "5TE Soil Probe 5cm"
  D5TE_VWC_15cm_Avg: "5TE Soil Probe 15cm"
  D5TE_EC_15cm_Avg: "5TE Soil Probe 15cm"
  D5TE_T_15cm_Avg: "5TE Soil Probe 15cm"
  D5TE_VWC_30cm_Avg: "5TE Soil Probe 30 cm"
  D5TE_EC_30cm_Avg: "5TE Soil Probe 30 cm"
  D5TE_T_30cm_Avg: "5TE Soil Probe 30 cm"
  D5TE_VWC_50cm_Avg: "5TE Soil Probe 50 cm"
  D5TE_EC_50cm_Avg: "5TE Soil Probe 50 cm"
  D5TE_T_50cm_Avg: "5TE Soil Probe 50 cm"
  D5TE_VWC_100cm_Avg: "5TE Soil Probe 100cm"
  D5TE_EC_100cm_Avg: "5TE Soil Probe 100cm"
  D5TE_T_100cm_Avg: "5TE Soil Probe 100cm"
  D5TE_VWC_200cm_Avg: "5TE Soil Probe 200cm"
  D5TE_EC_200cm_Avg: "5TE Soil Probe 200cm"
  D5TE_T_200cm_Avg: "5TE Soil Probe 200cm"
  Targ121TempC_Avg: "SI-121 Infrared Radiometer"
  Targ1H1TempC_Avg: "SI-1H1 Infrared Radiometer"
  short_up_Avg: "CMR4 Pyranometer (Kipp&Zonen)"
  short_dn_Avg: "CMR4 Pyranometer (Kipp&Zonen)"
  long_up_corr_Avg: "CMR4 Pyranometer (Kipp&Zonen)"
  long_dn_corr_Avg: "CMR4 Pyranometer (Kipp&Zonen)"
  Rs_net_Avg: "CMR4 Pyranometer (Kipp&Zonen)"
  Rl_net_Avg: "CMR4 Pyranometer (Kipp&Zonen)"
  albedo_Avg: "CMR4 Pyranometer (Kipp&Zonen)"
  Rn_Avg: "CMR4 Pyranometer (Kipp&Zonen)"
  SQ_110_Avg: "Campbell LI190SB-L (PAR)"
  shf_Avg(1): "HFP01SC-L50 (2 heat flux plates)"
  shf_Avg(2): "HFP01SC-L50 (2 heat flux plates)"
  DS2_WindSpeed_Max: "DS2 Sonic Anemometer"
  DS2_WindSpeed_Avg: "DS2 Sonic Anemometer"
  DS2_WindDir_Avg: "DS2 Sonic Anemometer"
  DS2_Temp_Avg: "DS2 Sonic Anemometer"
  mean_wind_speed: "Windsonic4"
  mean_wind_direction: "Windsonic4"
  std_wind_dir: "Windsonic4"
sensors:
  - "Li7500"
  - "CSAT3 Sonic Anemometer"
  - "083E Temp and RH"
  - "DS2 Sonic Anemometer"
  - "SRS NDVI (a:fieldstop): Nr"
  - "SRS NDVI (b: hemispherical): Ni"
  - "SRS PRI (a:fieldstop): Pr"
  - "SRS PRI (b: hemispherical): Pi"
  - "TE525-L rain gauge"
  - "SI-1H1 Infrared Radiometer"
  - "CMR4 Pyranometer (Kipp&Zonen)"
  - "SI-121 Infrared Radiometer"
  - "Campbell LI190SB-L (PAR)"
  - "5TE Soil Probe 5cm"
  - "5TE Soil Probe 15cm"
  - "5TE Soil Probe 30 cm"
  - "5TE Soil Probe 50 cm"
  - "5TE Soil Probe 100cm"
  - "5TE Soil Probe 200cm"
  - "CS655-L50 Reflectometer"
  - "HFP01SC-L50 (2 heat flux plates)"
  - "Windsonic4"
sensorscreate:
  - "Li7500"
  - "CSAT3 Sonic Anemometer"
  - "083E Temp and RH"
  - "DS2 Sonic Anemometer"
  - "SRS NDVI (a:fieldstop): Nr"
  - "SRS NDVI (b: hemispherical): Ni"
  - "SRS PRI (a:fieldstop): Pr"
  - "SRS PRI (b: hemispherical): Pi"
  - "TE525-L rain gauge"
  - "SI-1H1 Infrared Radiometer"
  - "CMR4 Pyranometer (Kipp&Zonen)"
  - "SI-121 Infrared Radiometer"
  - "Campbell LI190SB-L (PAR)"
  - "5TE Soil Probe 5cm"
  - "5TE Soil Probe 15cm"
  - "5TE Soil Probe 30 cm"
  - "5TE Soil Probe 50 cm"
  - "5TE Soil Probe 100cm"
  - "5TE Soil Probe 200cm"
  - "CS655-L50 Reflectometer"
  - "HFP01SC-L50 (2 heat flux plates)"
  - "Windsonic4"